server:
  port: 1008

spring:
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

cloud:
  retry:
    interval-in-seconds: 30

  trace:
    with-header: false

  jwt:
    app-id: 1008
    secret: sample.app20200808qa1z3838wsxedc3rfv4tgbyhnujm5ikolp9ttt$QA0ZWSXED2CRFV8TGB2YHNU7JM3IKO8LPa12*@(cloud.jwt)
    ttl-in-hours: 24
    multi-login-check: true

  oauth1:
    config-folder: /etc/sample/config
    config-name: oauth1-keys.json

  openapi:
    app-id: 2824
    app-key: F96502BD5D1D4224B55FE24503EFB52C