server:
  port: 1008

spring:
  redis:
    address:
      redis://192.168.92.56:6379,//192.168.92.64:6379,//192.168.92.65:6379,//192.168.92.56:6380,//192.168.92.64:6380,//192.168.92.65:6380

cloud:
  retry:
    interval-in-seconds: 30

  log:
    with-header: true

  jwt:
    app-id: 1008
    secret: sample.app20200808qa1z3838wsxedc3rfv4tgbyhnujm5ikolp9ttt$QA0ZWSXED2CRFV8TGB2YHNU7JM3IKO8LPa12*@(cloud.jwt)
    ttl-in-hours: 24
    multi-login-check: true

  oauth1:
    config-folder: /etc/sample/config
    config-name: oauth1-keys.json