server:
  port: 1008

spring:
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

cloud:
  retry:
    interval-in-seconds: 30

  trace:
    with-header: false

  jwt:
    app-id: 1008
    secret: sample.app20200808qa1z3838wsxedc3rfv4tgbyhnujm5ikolp9ttt$QA0ZWSXED2CRFV8TGB2YHNU7JM3IKO8LPa12*@(cloud.jwt)
    ttl-in-hours: 24
    multi-login-check: true

  oauth1:
    config-folder: /etc/sample/config
    config-name: oauth1-keys.json

  client:
    remote-service-1:
      url: $cloud.client.remote-service-1.url$
      consumer-key: $cloud.client.remote-service-1.consumer-key$
      consumer-secret: $cloud.client.remote-service-1.consumer-secret$
    remote-service-2:
      url: $cloud.client.remote-service-2.url$
    remote-service-3:
      url: $cloud.client.remote-service-3.url$
      app-id: $cloud.client.remote-service-3.app-id$
      app-key: $cloud.client.remote-service-3.app-key$